Repository mteu/typo3-monitoring, pull requests merged in 2025-07, with the labels that each got.

#11 [BUGFIX] Show AuthorizationHeader name in backend example
  Resources/Private/Templates/Backend/Monitoring.html
Labels: bug

#12 [TASK] Expand PHP version range in testing matrix
  .github/workflows/tests.yaml
Labels: maintenance

#15 [TASK] Publish extension to TER in release workflow
  .editorconfig
  .github/settings.yaml
  .github/workflows/release.yaml
  .gitignore
  Documentation/api.md
  Documentation/architecture.md
  Documentation/authorization.md
  Documentation/backend.md
  Documentation/command-line.md
  Documentation/configuration.md
  Documentation/middleware.md
  SECURITY.md
  composer.json
  composer.lock
  ext_emconf.php
  packaging_exclude.php
  typoscript-lint.yml
Labels: maintenance

#18 [BUGFIX] Fix TER Upload workflow
  .github/workflows/release.yaml
Labels: maintenance

#21 [DOCS] Integrate TYPO3 Badges
  README.md
Labels: documentation

#26 [!!!][TASK] Drop AbstractMonitoringResult in favor of a simpler solution
  Classes/Result/AbstractMonitoringResult.php
  Classes/Result/MonitoringResult.php
  Documentation/middleware.md
  Documentation/providers.md
Labels: breaking

#22 [TASK] Ignore `config` folder
  .gitignore
Labels: maintenance

#24 [BUGFIX] Trigger warning for unset secret
  Classes/Backend/Controller/MonitoringController.php
  README.md
  Resources/Private/Language/de.localllang.be.xlf
  Resources/Private/Language/locallang.be.xlf
  Resources/Private/Templates/Backend/Monitoring.html
Labels: bug

#30 [TASK] Minor language washing in localization files
  Resources/Private/Language/de.locallang.be.xlf
  Resources/Private/Language/locallang.be.xlf
Labels: maintenance

#31 [TASK] Beautify "no providers found" alert
  Resources/Private/Language/de.locallang.be.xlf
  Resources/Private/Language/locallang.be.xlf
  Resources/Private/Templates/Backend/Monitoring.html
Labels: maintenance

#34 [!!!][FEATURE] Provide Extension settings from a DTO with stricter types
  Classes/Authorization/AdminUserAuthorizer.php
  Classes/Authorization/Authorizer.php
  Classes/Authorization/TokenAuthorizer.php
  Classes/Backend/Controller/MonitoringController.php
  Classes/Configuration/Authorizer/AdminUserAuthorizerConfiguration.php
  Classes/Configuration/Authorizer/AuthorizerConfiguration.php
  Classes/Configuration/Authorizer/TokenAuthorizerConfiguration.php
  Classes/Configuration/Extension.php
  Classes/Configuration/MonitoringConfiguration.php
  Classes/Configuration/MonitoringConfigurationFactory.php
  Classes/Middleware/MonitoringMiddleware.php
  Documentation/authorization.md
  Documentation/configuration.md
  README.md
  Tests/Unit/Configuration/MonitoringConfigurationTest.php
  composer.json
  ext_conf_template.txt
  phpstan.inc.neon
  rector.php
Labels: breaking

#36 [TASK] Update package name in GPL
  Classes/Authorization/AdminUserAuthorizer.php
  Classes/Authorization/Authorizer.php
  Classes/Authorization/TokenAuthorizer.php
  Classes/Backend/Controller/MonitoringController.php
  Classes/Cache/CachedMonitoringResult.php
  Classes/Cache/MonitoringCacheManager.php
  Classes/Command/MonitoringCommand.php
  Classes/Configuration/Authorizer/AdminUserAuthorizerConfiguration.php
  Classes/Configuration/Authorizer/AuthorizerConfiguration.php
  Classes/Configuration/Authorizer/TokenAuthorizerConfiguration.php
  Classes/Configuration/MonitoringConfiguration.php
  Classes/Configuration/MonitoringConfigurationFactory.php
  Classes/Handler/MonitoringExecutionHandler.php
  Classes/Middleware/MonitoringMiddleware.php
  Classes/Provider/CacheableMonitoringProvider.php
  Classes/Provider/MonitoringProvider.php
  Classes/Result/MonitoringResult.php
  Classes/Result/Result.php
  Classes/Trait/SlugifyCacheKeyTrait.php
  Classes/ViewHelper/Backend/ClassNameViewHelper.php
  ext_emconf.php
  rector.php
Labels: maintenance

#38 [TASK] Upgrade PHPUnit to v12
  Tests/Unit/Trait/SlugifyCacheKeyTraitTest.php
  composer.json
  composer.lock
Labels: dependencies

#41 [FEATURE] Get type-safe extension configuration
  .gitattributes
  Classes/Authorization/AdminUserAuthorizer.php
  Classes/Authorization/TokenAuthorizer.php
  Classes/Backend/Controller/MonitoringController.php
  Classes/Configuration/Authorizer/AdminUserAuthorizerConfiguration.php
  Classes/Configuration/Authorizer/TokenAuthorizerConfiguration.php
  Classes/Configuration/MonitoringConfiguration.php
  Classes/Configuration/MonitoringConfigurationFactory.php
  Classes/Configuration/Provider/SelfCareProviderConfiguration.php
  Classes/Middleware/MonitoringMiddleware.php
  Classes/Provider/SelfCareProvider.php
  Tests/Unit/Configuration/Authorizer/AdminUserAuthorizerConfigurationTest.php
  Tests/Unit/Configuration/Authorizer/TokenAuthorizerConfigurationTest.php
  Tests/Unit/Configuration/MonitoringConfigurationTest.php
  Tests/Unit/Middleware/MonitoringMiddlewareTest.php
  composer.json
  composer.lock
  phpstan.inc.neon
Labels: enhancement

#43 [FEATURE] Add backward compatibility for TYPO3 v12
  .github/composer/composer.typo3-v12.json
  .github/workflows/tests.yaml
  Classes/ViewHelper/Backend/ClassNameViewHelper.php
  composer.json
  composer.lock
  ext_emconf.php
Labels: enhancement

#44 [BUGFIX] Reflect package dependencies in `ext_emconf.php`
  ext_emconf.php
Labels: bug

#46 [!!!][TASK] Demote `SelfCareProvider` to `MiddlewareStatusProvider`
  Classes/Backend/Controller/MonitoringController.php
  Classes/Middleware/MonitoringMiddleware.php
  Classes/Provider/MiddlewareStatusProvider.php
  Documentation/configuration.md
  Tests/Unit/ViewHelper/ClassNameViewHelperTest.php
Labels: breaking

#56 [TASK] Retrieve adequate HashService instance from factory
  Classes/Authorization/TokenAuthorizer.php
  Classes/Backend/Controller/MonitoringController.php
  Classes/Crypto/HashServiceFactory.php
  Classes/Provider/MiddlewareStatusProvider.php
  Tests/CGL/composer-dependency-analyser.php
Labels: maintenance

#54 [FEATURE] Display error for unexpected monitoring api behavior
  Classes/Authorization/TokenAuthorizer.php
  Classes/Backend/Controller/MonitoringController.php
  Classes/Configuration/MonitoringConfiguration.php
  Classes/Configuration/Provider/MiddlewareStatusProviderConfiguration.php
  Classes/Provider/MiddlewareStatusProvider.php
  Resources/Private/Language/de.locallang.be.xlf
  Resources/Private/Language/locallang.be.xlf
  Resources/Private/Templates/Backend/Monitoring.html
  Tests/Unit/Middleware/MonitoringMiddlewareTest.php
  Tests/Unit/Provider/MiddlewareStatusProviderTest.php
  Tests/Unit/ViewHelper/ClassNameViewHelperTest.php
  ext_conf_template.txt
Labels: enhancement

#57 [TASK] Align extension constraints with composer reqs
  ext_emconf.php
Labels: dependencies
